# Generated by Django 6.0.5 on 2026-05-21 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Identificador único. Ej: max_upload_size', max_length=100, unique=True, verbose_name='clave')),
                ('value', models.TextField(help_text='Siempre almacenado como texto.', verbose_name='valor')),
                ('value_type', models.CharField(choices=[('str', 'Texto'), ('int', 'Entero'), ('bool', 'Booleano'), ('json', 'JSON')], default='str', max_length=10, verbose_name='tipo de valor')),
                ('description', models.TextField(blank=True, help_text='Propósito legible de esta configuración.', verbose_name='descripción')),
                ('is_public', models.BooleanField(default=False, help_text='Si está marcada, se expone en el contexto de templates.', verbose_name='pública')),
            ],
            options={
                'verbose_name': 'configuración del sitio',
                'verbose_name_plural': 'configuraciones del sitio',
                'ordering': ['key'],
            },
        ),
    ]
