# Generated by Django 6.0.5 on 2026-05-22 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='teléfono')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='empresa')),
                ('status', models.CharField(choices=[('lead', 'Lead'), ('prospect', 'Prospecto'), ('client', 'Cliente'), ('inactive', 'Inactivo')], default='lead', max_length=20, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='duración (minutos)')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('date', models.DateTimeField(verbose_name='fecha')),
                ('direction', models.CharField(choices=[('in', 'Entrante'), ('out', 'Saliente')], max_length=3, verbose_name='dirección')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='crm_demo.contact', verbose_name='contacto')),
            ],
            options={
                'verbose_name': 'Llamada',
                'verbose_name_plural': 'Llamadas',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='asunto')),
                ('body', models.TextField(blank=True, verbose_name='cuerpo')),
                ('date', models.DateTimeField(verbose_name='fecha')),
                ('direction', models.CharField(choices=[('in', 'Entrante'), ('out', 'Saliente')], max_length=3, verbose_name='dirección')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='crm_demo.contact', verbose_name='contacto')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='monto')),
                ('description', models.CharField(max_length=300, verbose_name='descripción')),
                ('date', models.DateField(verbose_name='fecha')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='crm_demo.contact', verbose_name='contacto')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('facebook', 'Facebook')], max_length=20, verbose_name='red social')),
                ('url', models.URLField(verbose_name='URL')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_profiles', to='crm_demo.contact', verbose_name='contacto')),
            ],
            options={
                'verbose_name': 'Perfil social',
                'verbose_name_plural': 'Perfiles sociales',
                'unique_together': {('contact', 'network')},
            },
        ),
    ]
