# Generated by Django 6.0.5 on 2026-05-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='teléfono')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['-created_at'],
            },
        ),
    ]
