# Generated by Django 6.0.5 on 2026-05-21 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Crear'), ('update', 'Actualizar'), ('delete', 'Eliminar'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('view', 'Ver')], max_length=20, verbose_name='acción')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='modelo')),
                ('object_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID objeto')),
                ('object_repr', models.CharField(max_length=200, verbose_name='representación del objeto')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='cambios')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='dirección IP')),
                ('user_agent', models.CharField(blank=True, max_length=300, null=True, verbose_name='user agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'registro de auditoría',
                'verbose_name_plural': 'registros de auditoría',
                'ordering': ['-timestamp'],
            },
        ),
    ]
