# Generated by Django 6.0.5 on 2026-05-21 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('body', models.TextField(verbose_name='cuerpo')),
                ('channel', models.CharField(choices=[('in_app', 'En la app'), ('email', 'Email'), ('webhook', 'Webhook')], max_length=20, verbose_name='canal')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='leída el')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='enviada el')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Datos adicionales para webhooks.', verbose_name='payload')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada el')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='destinatario')),
            ],
            options={
                'verbose_name': 'notificación',
                'verbose_name_plural': 'notificaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('secret', models.CharField(blank=True, help_text='Usado para firmar el payload con HMAC-SHA256.', max_length=200, verbose_name='secreto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'endpoint webhook',
                'verbose_name_plural': 'endpoints webhook',
            },
        ),
    ]
